"""add_cascade_delete_to_balances_and_deadlines

Revision ID: 4aca2152ea66
Revises: 507dd5272869
Create Date: 2026-03-22 00:28:58.175968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aca2152ea66'
down_revision: Union[str, Sequence[str], None] = '507dd5272869'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('balances_company_id_fkey'), 'balances', type_='foreignkey')
    op.create_foreign_key(None, 'balances', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('deadlines_company_id_fkey'), 'deadlines', type_='foreignkey')
    op.create_foreign_key(None, 'deadlines', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deadlines', type_='foreignkey')
    op.create_foreign_key(op.f('deadlines_company_id_fkey'), 'deadlines', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.create_foreign_key(op.f('balances_company_id_fkey'), 'balances', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###
